CREATE TABLE branch (
                        id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        nome VARCHAR2(255) NOT NULL,
                        bairro VARCHAR2(255) NOT NULL,
                        cnpj VARCHAR2(20) NOT NULL
);

CREATE TABLE patio (
                       id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       nome VARCHAR2(255) NOT NULL,
                       branch_id NUMBER NOT NULL,
                       CONSTRAINT fk_patio_branch FOREIGN KEY (branch_id)
                           REFERENCES branch (id)
                           ON DELETE CASCADE
);

CREATE TABLE motorcycle (
                            id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            placa VARCHAR2(7) NOT NULL UNIQUE,
                            chassi VARCHAR2(17) NOT NULL UNIQUE,
                            numeracao_motor VARCHAR2(17) NOT NULL,
                            motorcycle_models VARCHAR2(255) NOT NULL,
                            patio_id NUMBER,
                            situacao VARCHAR2(255) NOT NULL,
                            CONSTRAINT fk_motorcycle_patio FOREIGN KEY (patio_id)
                                REFERENCES patio (id)
                                ON DELETE SET NULL
);

CREATE TABLE motorcycle_groups (
                                   motorcycle_id NUMBER NOT NULL,
                                   model VARCHAR2(50) NOT NULL,
                                   CONSTRAINT fk_motorcycle_groups FOREIGN KEY (motorcycle_id)
                                       REFERENCES motorcycle (id)
                                       ON DELETE CASCADE
);
