CREATE TABLE users (
                       id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       username VARCHAR2(50) NOT NULL UNIQUE,
                       password VARCHAR2(255) NOT NULL
);

CREATE TABLE user_roles (
                            user_id NUMBER NOT NULL,
                            roles VARCHAR2(20) NOT NULL,
                            CONSTRAINT fk_user_roles FOREIGN KEY (user_id)
                                REFERENCES users (id)
);
